DATABASE_IMAGE_HEIGHT = 100
DATABASE_IMAGE_WIDTH = 100

ALLOW_USE_EXISING_IF_SEEM_SAME = True

MIN_ITEMS_PER_THREAD = 10

MAX_THREAD_PER_PROCESS = 1

# XXX if change variables below, it will re-create your database

IMAGES_FOLDER = 'images'
DATABASE_FILE = 'database'
POSTFIX = 'data'

DATABASE_FOLDER = '{folder}.' + POSTFIX

MAX_CACHE_PROCESSED_IMAGES = 1000